### ISSUE TITLE
rainbowstream is not working

### ISSUE THREAD

**Issue by bessarabov** [jfrazelle/dockerfiles#13]
```
$ docker run jess/rainbowstream
You are running latest version (1.2.7)
Hi there! We're gonna get you all set up to use Rainbow Stream.

In the web browser window that opens please choose to Allow
access. Copy the PIN number that appears on the next page and paste or
type it here:

Opening: https://api.twitter.com/oauth/authorize?oauth_token=rMt4L5T41BV4mhxVGy0CM8nq6To4h0MR


Uh, I couldn't open a browser on your computer. Please go here to get
your PIN:

https://api.twitter.com/oauth/authorize?oauth_token=rMt4L5T41BV4mhxVGy0CM8nq6To4h0MR
Please enter the PIN: Traceback (most recent call last):
  File "/usr/local/bin/rainbowstream", line 9, in <module>
    load_entry_point('rainbowstream==1.2.7', 'console_scripts', 'rainbowstream')()
  File "/usr/local/lib/python3.4/site-packages/rainbowstream/rainbow.py", line 2192, in fly
    init(args)
  File "/usr/local/lib/python3.4/site-packages/rainbowstream/rainbow.py", line 206, in init
    t = Twitter(auth=authen())
  File "/usr/local/lib/python3.4/site-packages/rainbowstream/rainbow.py", line 126, in authen
    twitter_credential)
  File "/usr/local/lib/python3.4/site-packages/twitter/oauth_dance.py", line 75, in oauth_dance
    oauth_verifier = _input("Please enter the PIN: ").strip()
EOFError: EOF when reading a line

$ docker images jess/rainbowstream
REPOSITORY           TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
jess/rainbowstream   latest              530d30d26fb9        4 days ago          791 MB

$ docker --version
Docker version 1.5.0, build a8a31ef
```

**Comment by bessarabov** [comment]
I'm sorry. It works ok. I just needed to run `docker run -it jess/rainbowstream`
