### ISSUE TITLE
Error on Sublime Text 3 & Package Control

### ISSUE THREAD

**Issue by romqin** [jfrazelle/dockerfiles#88]
Hi,

When I start sublime text, I got this error:
```
Your system's locale is set to a value that can not handle non-ASCII characters. Package Control can not properly work unless this is fixed.

On Linux, please reference your distribution's docs for information on properly setting the LANG environmental variable. As a temporary work-around, you can launch Sublime Text from the terminal with:

LANG=en_US.UTF-8 sublime_text
```

So I tried to add `-e LANG=en_US.UTF-8` in the docker command but I still have the error.

I try to install plugin on sublime text 3 with [package control](https://packagecontrol.io/installation).
But when I do *CTRL+SHIFT+P* then *Install Package* nothing append and here is the console stacktrace:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in /root/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 46, in run
  File "package_control.package_installer in /root/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 92, in make_package_list
  File "package_control.package_manager in /root/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 246, in is_vcs_package
  File "package_control.package_manager in /root/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 221, in _is_git_package
  File "./genericpath.py", line 18, in exists
UnicodeEncodeError: 'ascii' codec can't encode character '\xea' in position 78: ordinal not in range(128)
```

Have you any idea how to fix this ?

**Comment by koep** [comment]
Hi,

I launch sublime-text with the following command:

```bash
docker run -d \
-e DISPLAY=unix$DISPLAY \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-v $HOME/.config/sublime-text-3/:/root/.config/sublime-text-3 \
-v $HOME/development:/root/development \
--name sublime-text \
-h sublime-text \
sublime-text:3
```

on Arch Linux (Kernel 4.2.5-1-ARCH) and I do not get this error.

What distro are you using?

**Comment by koep** [comment]
Maybe this works for you: https://github.com/wbond/package_control/issues/532#issuecomment-59430511

**Comment by romqin** [comment]
I am on ubuntu 15.10
I will try your docker command, but I think that the only difference with mine is the `-h sublime-text`

**Comment by koep** [comment]
You might have to take a look at https://github.com/jfrazelle/dockerfiles/issues/88#issuecomment-162799448 and play around with environment variables (e.g unset $LC_ALL inside the container).
